### ISSUE TITLE
TreeIndex construction improvements

### ISSUE THREAD

**Issue by irakliyk** [novifinancial/smtree#9]
It seems like the proper way to construct a `TreeIndex` right now is to use `utils::set_pos_best()` rather than `TreeIndex::new()`. It might be good to move this function into `TreeIndex` implementation - and maybe make the current constructor private. There could also be multiple constructors: `from_u32()`, `from_u64()` etc.

**Comment by kchalkias** [comment]
Done in https://github.com/novifinancial/smtree/pull/10 and https://github.com/novifinancial/smtree/pull/11
